### ISSUE TITLE
Possible to turn off the default implemented commands?

### ISSUE THREAD

**Issue by lifehome** [michaelimfeld/ownbot#10]
I mean, it's good, but I just simply don't want them, nor I want to fork(bit lazy recently). Is it possible to configure this project a bit, so that the default commands like `/adminhelp` and `/adduser` are inaccessible to anyone, including the owner/whatsoever-admins?

**Comment by michaelimfeld** [comment]
Hi
You can just skip/remove the AdminCommands line:

```python
AdminCommands(dispatcher)
```
That should do the trick:)

**Comment by lifehome** [comment]
Thanks!
