### ISSUE TITLE
Change parse_type to HTML 

### ISSUE THREAD

**Issue by s-chizhik** [michaelimfeld/ownbot#9]
Hi! I've noticed, that users with `_` character, crashes `/users` command. It happens, cause users list sends with Markdown parse mode, and user nickname with single `_` char (unclosed tag) leads to the exception:
> Bad Request: can't parse message text: Can't find end of the entity starting at byte offset ...

I guess changing parse mode to HTML will fix this problem. Can I send PR to you?

**Comment by michaelimfeld** [comment]
Hi

I think we have to sanitize the users input/username somehow or do proper error handling. 
Using the html parser would not really fix this issue since your name could contain html tags (?)
You can open a PR for further discussion. I will look into it :)

Cheers

**Comment by s-chizhik** [comment]
Hm, I guess escaping user input is a better idea. I'll send you PR ;)

**Comment by s-chizhik** [comment]
Just now, I realized, that we still can change parse mode to `HTML`, and use `html.escape` to do the job. What do you say?

**Comment by michaelimfeld** [comment]
Sounds good to me :+1:  
Feel free to send me a PR.

Cheers
